"""Initial

Revision ID: 0c19018a5ea6
Revises:
Create Date: 2026-07-27 22:37:58.532061

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0c19018a5ea6'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'candidates',
        sa.Column('identifier', sa.String(length=255), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
        sa.Column('request_count', sa.Integer(), nullable=False),
        sa.Column(
            'last_request_at', sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_candidates_identifier'),
        'candidates',
        ['identifier'],
        unique=True,
    )
    op.create_table(
        'files',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('size', sa.BigInteger(), nullable=False),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_files_name'), 'files', ['name'], unique=True)
    op.create_table(
        'downloaded_files',
        sa.Column('candidate_id', sa.BigInteger(), nullable=False),
        sa.Column('file_id', sa.BigInteger(), nullable=False),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['candidate_id'], ['candidates.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'candidate_id', 'file_id', name='uq_candidate_file'
        ),
    )
    op.create_index(
        op.f('ix_downloaded_files_candidate_id'),
        'downloaded_files',
        ['candidate_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_downloaded_files_file_id'),
        'downloaded_files',
        ['file_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_downloaded_files_file_id'), table_name='downloaded_files'
    )
    op.drop_index(
        op.f('ix_downloaded_files_candidate_id'), table_name='downloaded_files'
    )
    op.drop_table('downloaded_files')
    op.drop_index(op.f('ix_files_name'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_candidates_identifier'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
